[AxisMapping]
steering = 0
throttle = 1
brake = 2
joy_reverse = 4
joy_handbrake = 4
joy_hide_hud = 7
joy_toggle_headlights = 1

# 'A' key
joy_next_trial = 0

steering_damping = 0.3  
throttle_damping = 0.8  
brake_damping = 1.5  
random_vehicle = False
default_vehicle = vehicle.tesla.model3
speed_unit = mph
height_unit = ft
joy_shifter_drive = 12
joy_shifter_neutral = 13
joy_shifter_reverse = 17

[Settings]
steering_damping = 0.3  
throttle_damping = 0.8  
brake_damping = 1.5  
random_vehicle = False
default_vehicle = vehicle.tesla.model3

speed_unit = mph
height_unit = ft

[KeyMapping]
key_reverse = q
key_handbrake = k
key_hide_hud = o
key_toggle_headlights = l
key_joystick = 7
key_keyboard = o
key_shifter_drive = i
key_shifter_neutral = h
key_shifter_reverse = j

[TrialSettings]
# 24236.615234/100.0
location_x = 242.36615234
# -1008.180115/100
location_y = -10.08180115
# 27.530716/100
location_z = 0.27530716

rotation_pitch = 0.0
rotation_yaw = -88.606766
rotation_roll = 0.0
speed_limit = 45.0
max_speed_limit = 50.0
data_save_location = C:\carla_env\fgcu-carla-UPDATED\data\